version: '3'
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--protected-mode", "no"]
    ports:
      - "6379:6379"
      - "15672:15672"
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  fee-service:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    environment:
      PORT: 3000
      LOG_LEVEL: debug
      CHAIN_ID: 137
      REDIS_URL: redis://localhost:6379
      MONGODB_URL: localhost:27017
      MONGODB_DB: collected-fee
volumes:
    mongo-data:
