version: '3'
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--protected-mode", "no"]
    ports:
      - "6379:6379"
      - "15672:15672"
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
